//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coderush.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_DON
    {
        public int IDCHITIETHOADON { get; set; }
        public string MAHOADON { get; set; }
        public string MAMON { get; set; }
        public int SOLUONG { get; set; }
        public decimal GIA { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual MON MON { get; set; }
    }
}
